sudo: required
language: generic 
services: 
  - docker

before_install: 
  - docker build -t mccs0064/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run mccs0064/react-test npm run test -- --coverage

after_success: 
  - docker build -t mccs0064/multi-client ./client
  - docker build -t mccs0064/multi-nginx ./nginx
  - docker build -t mccs0064/multi-server ./server
  - docker build -t mccs0064/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mccs0064/multi-client 
  - docker push mccs0064/multi-nginx
  - docker push mccs0064/multi-server
  - docker push mccs0064/multi-worker
   
deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-931335830251"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
